proto_library(
    name = "tracer_configuration_proto",
    srcs = ["tracer_configuration.proto"],
    deps = [],
    visibility = ["//visibility:public"],
)

cc_proto_library(
    name = "tracer_configuration_proto_cc",
    deps = [":tracer_configuration_proto"],
    visibility = ["//visibility:public"],
)

