// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: envoy_carrier.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "envoy_carrier.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace lightstep {
namespace envoy {

namespace {

const ::google::protobuf::Descriptor* CarrierPair_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CarrierPair_reflection_ = NULL;
const ::google::protobuf::Descriptor* CarrierFormat_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CarrierFormat_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_envoy_5fcarrier_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_envoy_5fcarrier_2eproto() {
  protobuf_AddDesc_envoy_5fcarrier_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "envoy_carrier.proto");
  GOOGLE_CHECK(file != NULL);
  CarrierPair_descriptor_ = file->message_type(0);
  static const int CarrierPair_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarrierPair, key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarrierPair, value_),
  };
  CarrierPair_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CarrierPair_descriptor_,
      CarrierPair::default_instance_,
      CarrierPair_offsets_,
      -1,
      -1,
      -1,
      sizeof(CarrierPair),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarrierPair, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarrierPair, _is_default_instance_));
  CarrierFormat_descriptor_ = file->message_type(1);
  static const int CarrierFormat_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarrierFormat, context_),
  };
  CarrierFormat_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CarrierFormat_descriptor_,
      CarrierFormat::default_instance_,
      CarrierFormat_offsets_,
      -1,
      -1,
      -1,
      sizeof(CarrierFormat),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarrierFormat, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarrierFormat, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_envoy_5fcarrier_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CarrierPair_descriptor_, &CarrierPair::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CarrierFormat_descriptor_, &CarrierFormat::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_envoy_5fcarrier_2eproto() {
  delete CarrierPair::default_instance_;
  delete CarrierPair_reflection_;
  delete CarrierFormat::default_instance_;
  delete CarrierFormat_reflection_;
}

void protobuf_AddDesc_envoy_5fcarrier_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_envoy_5fcarrier_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023envoy_carrier.proto\022\017lightstep.envoy\")"
    "\n\013CarrierPair\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001("
    "\t\">\n\rCarrierFormat\022-\n\007context\030\001 \003(\0132\034.li"
    "ghtstep.envoy.CarrierPairb\006proto3", 153);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "envoy_carrier.proto", &protobuf_RegisterTypes);
  CarrierPair::default_instance_ = new CarrierPair();
  CarrierFormat::default_instance_ = new CarrierFormat();
  CarrierPair::default_instance_->InitAsDefaultInstance();
  CarrierFormat::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_envoy_5fcarrier_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_envoy_5fcarrier_2eproto {
  StaticDescriptorInitializer_envoy_5fcarrier_2eproto() {
    protobuf_AddDesc_envoy_5fcarrier_2eproto();
  }
} static_descriptor_initializer_envoy_5fcarrier_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CarrierPair::kKeyFieldNumber;
const int CarrierPair::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CarrierPair::CarrierPair()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:lightstep.envoy.CarrierPair)
}

void CarrierPair::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

CarrierPair::CarrierPair(const CarrierPair& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:lightstep.envoy.CarrierPair)
}

void CarrierPair::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

CarrierPair::~CarrierPair() {
  // @@protoc_insertion_point(destructor:lightstep.envoy.CarrierPair)
  SharedDtor();
}

void CarrierPair::SharedDtor() {
  key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void CarrierPair::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CarrierPair::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CarrierPair_descriptor_;
}

const CarrierPair& CarrierPair::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_envoy_5fcarrier_2eproto();
  return *default_instance_;
}

CarrierPair* CarrierPair::default_instance_ = NULL;

CarrierPair* CarrierPair::New(::google::protobuf::Arena* arena) const {
  CarrierPair* n = new CarrierPair;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CarrierPair::Clear() {
// @@protoc_insertion_point(message_clear_start:lightstep.envoy.CarrierPair)
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool CarrierPair::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:lightstep.envoy.CarrierPair)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string key = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->key().data(), this->key().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "lightstep.envoy.CarrierPair.key"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_value;
        break;
      }

      // optional string value = 2;
      case 2: {
        if (tag == 18) {
         parse_value:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->value().data(), this->value().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "lightstep.envoy.CarrierPair.value"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:lightstep.envoy.CarrierPair)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:lightstep.envoy.CarrierPair)
  return false;
#undef DO_
}

void CarrierPair::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:lightstep.envoy.CarrierPair)
  // optional string key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), this->key().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "lightstep.envoy.CarrierPair.key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->key(), output);
  }

  // optional string value = 2;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "lightstep.envoy.CarrierPair.value");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->value(), output);
  }

  // @@protoc_insertion_point(serialize_end:lightstep.envoy.CarrierPair)
}

::google::protobuf::uint8* CarrierPair::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:lightstep.envoy.CarrierPair)
  // optional string key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), this->key().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "lightstep.envoy.CarrierPair.key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->key(), target);
  }

  // optional string value = 2;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "lightstep.envoy.CarrierPair.value");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->value(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:lightstep.envoy.CarrierPair)
  return target;
}

int CarrierPair::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:lightstep.envoy.CarrierPair)
  int total_size = 0;

  // optional string key = 1;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->key());
  }

  // optional string value = 2;
  if (this->value().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->value());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CarrierPair::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:lightstep.envoy.CarrierPair)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const CarrierPair* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CarrierPair>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:lightstep.envoy.CarrierPair)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:lightstep.envoy.CarrierPair)
    MergeFrom(*source);
  }
}

void CarrierPair::MergeFrom(const CarrierPair& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:lightstep.envoy.CarrierPair)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.key().size() > 0) {

    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  if (from.value().size() > 0) {

    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
}

void CarrierPair::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:lightstep.envoy.CarrierPair)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CarrierPair::CopyFrom(const CarrierPair& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lightstep.envoy.CarrierPair)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CarrierPair::IsInitialized() const {

  return true;
}

void CarrierPair::Swap(CarrierPair* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CarrierPair::InternalSwap(CarrierPair* other) {
  key_.Swap(&other->key_);
  value_.Swap(&other->value_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CarrierPair::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CarrierPair_descriptor_;
  metadata.reflection = CarrierPair_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CarrierPair

// optional string key = 1;
void CarrierPair::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& CarrierPair::key() const {
  // @@protoc_insertion_point(field_get:lightstep.envoy.CarrierPair.key)
  return key_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CarrierPair::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:lightstep.envoy.CarrierPair.key)
}
 void CarrierPair::set_key(const char* value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:lightstep.envoy.CarrierPair.key)
}
 void CarrierPair::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:lightstep.envoy.CarrierPair.key)
}
 ::std::string* CarrierPair::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:lightstep.envoy.CarrierPair.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* CarrierPair::release_key() {
  // @@protoc_insertion_point(field_release:lightstep.envoy.CarrierPair.key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CarrierPair::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:lightstep.envoy.CarrierPair.key)
}

// optional string value = 2;
void CarrierPair::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& CarrierPair::value() const {
  // @@protoc_insertion_point(field_get:lightstep.envoy.CarrierPair.value)
  return value_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CarrierPair::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:lightstep.envoy.CarrierPair.value)
}
 void CarrierPair::set_value(const char* value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:lightstep.envoy.CarrierPair.value)
}
 void CarrierPair::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:lightstep.envoy.CarrierPair.value)
}
 ::std::string* CarrierPair::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:lightstep.envoy.CarrierPair.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* CarrierPair::release_value() {
  // @@protoc_insertion_point(field_release:lightstep.envoy.CarrierPair.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CarrierPair::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:lightstep.envoy.CarrierPair.value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CarrierFormat::kContextFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CarrierFormat::CarrierFormat()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:lightstep.envoy.CarrierFormat)
}

void CarrierFormat::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

CarrierFormat::CarrierFormat(const CarrierFormat& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:lightstep.envoy.CarrierFormat)
}

void CarrierFormat::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

CarrierFormat::~CarrierFormat() {
  // @@protoc_insertion_point(destructor:lightstep.envoy.CarrierFormat)
  SharedDtor();
}

void CarrierFormat::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CarrierFormat::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CarrierFormat::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CarrierFormat_descriptor_;
}

const CarrierFormat& CarrierFormat::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_envoy_5fcarrier_2eproto();
  return *default_instance_;
}

CarrierFormat* CarrierFormat::default_instance_ = NULL;

CarrierFormat* CarrierFormat::New(::google::protobuf::Arena* arena) const {
  CarrierFormat* n = new CarrierFormat;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CarrierFormat::Clear() {
// @@protoc_insertion_point(message_clear_start:lightstep.envoy.CarrierFormat)
  context_.Clear();
}

bool CarrierFormat::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:lightstep.envoy.CarrierFormat)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .lightstep.envoy.CarrierPair context = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_context:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_context()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_context;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:lightstep.envoy.CarrierFormat)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:lightstep.envoy.CarrierFormat)
  return false;
#undef DO_
}

void CarrierFormat::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:lightstep.envoy.CarrierFormat)
  // repeated .lightstep.envoy.CarrierPair context = 1;
  for (unsigned int i = 0, n = this->context_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->context(i), output);
  }

  // @@protoc_insertion_point(serialize_end:lightstep.envoy.CarrierFormat)
}

::google::protobuf::uint8* CarrierFormat::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:lightstep.envoy.CarrierFormat)
  // repeated .lightstep.envoy.CarrierPair context = 1;
  for (unsigned int i = 0, n = this->context_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->context(i), false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:lightstep.envoy.CarrierFormat)
  return target;
}

int CarrierFormat::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:lightstep.envoy.CarrierFormat)
  int total_size = 0;

  // repeated .lightstep.envoy.CarrierPair context = 1;
  total_size += 1 * this->context_size();
  for (int i = 0; i < this->context_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->context(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CarrierFormat::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:lightstep.envoy.CarrierFormat)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const CarrierFormat* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CarrierFormat>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:lightstep.envoy.CarrierFormat)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:lightstep.envoy.CarrierFormat)
    MergeFrom(*source);
  }
}

void CarrierFormat::MergeFrom(const CarrierFormat& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:lightstep.envoy.CarrierFormat)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  context_.MergeFrom(from.context_);
}

void CarrierFormat::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:lightstep.envoy.CarrierFormat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CarrierFormat::CopyFrom(const CarrierFormat& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lightstep.envoy.CarrierFormat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CarrierFormat::IsInitialized() const {

  return true;
}

void CarrierFormat::Swap(CarrierFormat* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CarrierFormat::InternalSwap(CarrierFormat* other) {
  context_.UnsafeArenaSwap(&other->context_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CarrierFormat::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CarrierFormat_descriptor_;
  metadata.reflection = CarrierFormat_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CarrierFormat

// repeated .lightstep.envoy.CarrierPair context = 1;
int CarrierFormat::context_size() const {
  return context_.size();
}
void CarrierFormat::clear_context() {
  context_.Clear();
}
const ::lightstep::envoy::CarrierPair& CarrierFormat::context(int index) const {
  // @@protoc_insertion_point(field_get:lightstep.envoy.CarrierFormat.context)
  return context_.Get(index);
}
::lightstep::envoy::CarrierPair* CarrierFormat::mutable_context(int index) {
  // @@protoc_insertion_point(field_mutable:lightstep.envoy.CarrierFormat.context)
  return context_.Mutable(index);
}
::lightstep::envoy::CarrierPair* CarrierFormat::add_context() {
  // @@protoc_insertion_point(field_add:lightstep.envoy.CarrierFormat.context)
  return context_.Add();
}
::google::protobuf::RepeatedPtrField< ::lightstep::envoy::CarrierPair >*
CarrierFormat::mutable_context() {
  // @@protoc_insertion_point(field_mutable_list:lightstep.envoy.CarrierFormat.context)
  return &context_;
}
const ::google::protobuf::RepeatedPtrField< ::lightstep::envoy::CarrierPair >&
CarrierFormat::context() const {
  // @@protoc_insertion_point(field_list:lightstep.envoy.CarrierFormat.context)
  return context_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace envoy
}  // namespace lightstep

// @@protoc_insertion_point(global_scope)
