/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "lightstep_constants.h"

namespace lightstep_thrift {

const lightstepConstants g_lightstep_constants;

lightstepConstants::lightstepConstants() {
}

} // namespace

