/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef lightstep_CONSTANTS_H
#define lightstep_CONSTANTS_H

#include "lightstep_types.h"

namespace lightstep_thrift {

class lightstepConstants {
 public:
  lightstepConstants();

};

extern const lightstepConstants g_lightstep_constants;

} // namespace

#endif
