#ifndef LIGHTSTEP_TRACER_H
#define LIGHTSTEP_TRACER_H

#include <opentracing/tracer.h>
#include <opentracing/value.h>
#include <memory>
#include <unordered_map>

namespace lightstep {
struct TracerOptions {
	// AccessToken is the unique API key for your LightStep project.  It is
	// available on your account page at https://app.lightstep.com/account
  std::string access_token;

  // The host, port, and encryption option to use for the collector.
  std::string collector_host = "collector-grpc.lightstep.com";
  uint32_t    collector_port = 443;
  std::string collector_encryption = "tls";

	// `tags` are arbitrary key-value pairs that apply to all spans generated by
	// this Tracer.
  std::unordered_map<std::string, opentracing::Value> tags;

	// `max_buffered_spans` is the maximum number of spans that will be buffered
	// before sending them to a collector.
  size_t max_buffered_spans = 2000;

  // `reporting_period` is the maximum duration of time between sending spans
  // to a collector.  If zero, the default will be used.
  std::chrono::steady_clock::duration reporting_period =
      std::chrono::milliseconds(500);

  std::chrono::system_clock::duration report_timeout =
      std::chrono::seconds(5);
};

std::shared_ptr<opentracing::Tracer> make_lightstep_tracer(
    const TracerOptions& options) noexcept;
}  // namespace lightstep

#endif // LIGHTSTEP_TRACER_H
