// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: collector.proto
#ifndef GRPC_collector_2eproto__INCLUDED
#define GRPC_collector_2eproto__INCLUDED

#include "collector.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace lightstep {
namespace collector {

class CollectorService GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Report(::grpc::ClientContext* context, const ::lightstep::collector::ReportRequest& request, ::lightstep::collector::ReportResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::lightstep::collector::ReportResponse>> AsyncReport(::grpc::ClientContext* context, const ::lightstep::collector::ReportRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::lightstep::collector::ReportResponse>>(AsyncReportRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::lightstep::collector::ReportResponse>* AsyncReportRaw(::grpc::ClientContext* context, const ::lightstep::collector::ReportRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Report(::grpc::ClientContext* context, const ::lightstep::collector::ReportRequest& request, ::lightstep::collector::ReportResponse* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::lightstep::collector::ReportResponse>> AsyncReport(::grpc::ClientContext* context, const ::lightstep::collector::ReportRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::lightstep::collector::ReportResponse>>(AsyncReportRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::lightstep::collector::ReportResponse>* AsyncReportRaw(::grpc::ClientContext* context, const ::lightstep::collector::ReportRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_Report_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Report(::grpc::ServerContext* context, const ::lightstep::collector::ReportRequest* request, ::lightstep::collector::ReportResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Report : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Report() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Report() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Report(::grpc::ServerContext* context, const ::lightstep::collector::ReportRequest* request, ::lightstep::collector::ReportResponse* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReport(::grpc::ServerContext* context, ::lightstep::collector::ReportRequest* request, ::grpc::ServerAsyncResponseWriter< ::lightstep::collector::ReportResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Report<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Report : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Report() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Report() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Report(::grpc::ServerContext* context, const ::lightstep::collector::ReportRequest* request, ::lightstep::collector::ReportResponse* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
};

}  // namespace collector
}  // namespace lightstep


#endif  // GRPC_collector_2eproto__INCLUDED
