load(
    "//bazel:lightstep_build_system.bzl",
    "lightstep_cc_library",
    "lightstep_package",
)

lightstep_package()

lightstep_cc_library(
  name = "time_lib",
  private_hdrs = [
      "time.h",
  ],
)
