set(PROTO_PATH "${CMAKE_SOURCE_DIR}/configuration-proto")

set(UPLOAD_BENCHMARK_CONFIGURATION_PROTO ${PROTO_PATH}/upload_benchmark_configuration.proto)
set(GENERATED_PROTOBUF_PATH ${CMAKE_BINARY_DIR}/generated/configuration-proto)
file(MAKE_DIRECTORY ${GENERATED_PROTOBUF_PATH})

set(UPLOAD_BENCHMARK_CONFIGURATION_PB_CPP_FILE ${GENERATED_PROTOBUF_PATH}/upload_benchmark_configuration.pb.cc)
set(UPLOAD_BENCHMARK_CONFIGURATION_PB_H_FILE ${GENERATED_PROTOBUF_PATH}/upload_benchmark_configuration.pb.h)

add_custom_command(
  OUTPUT ${UPLOAD_BENCHMARK_CONFIGURATION_PB_CPP_FILE}
         ${UPLOAD_BENCHMARK_CONFIGURATION_PB_H_FILE}
 COMMAND ${PROTOBUF_PROTOC_EXECUTABLE}
 ARGS "--proto_path=${PROTO_PATH}"
      "--cpp_out=${GENERATED_PROTOBUF_PATH}"
      ${UPLOAD_BENCHMARK_CONFIGURATION_PROTO}
)

include_directories(SYSTEM ${GENERATED_PROTOBUF_PATH})
include_directories(SYSTEM ${GENERATED_PROTOBUF_PATH}/../)

add_library(upload_benchmark_configuration OBJECT ${UPLOAD_BENCHMARK_CONFIGURATION_PB_CPP_FILE})
